# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

deployment:
  staging:
    branch: master
    heroku:
      appname: polar-woodland-61016
  production:
    branch: production
    heroku:
      appname: polar-woodland-61016